version: '3.3'
services:
  json_rpc_server:
    container_name: json_rpc_server
    build: .docker
    command: tail -f /dev/null
    volumes:
      - ./:/var/www/json_rpc_server
      - ~/.ssh/:/root/.ssh/
    working_dir: /var/www/json_rpc_server
